name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install
        run: yarn bootstrap
      - name: Build
        run: lerna run build --ignore @vizzuality/layer-manager-docs
      - name: Test
        run: lerna run test --ignore @vizzuality/layer-manager-docs
